# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Game Time')),
                ('score_home', models.IntegerField()),
                ('score_away', models.IntegerField()),
                ('type', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('event', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
                ('nationality', models.IntegerField()),
                ('external_id_type', models.IntegerField()),
                ('external_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpirtScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_category', models.IntegerField()),
                ('score', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('division', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=50)),
                ('date_begin', models.DateTimeField(verbose_name='Begin Date')),
                ('date_end', models.DateTimeField(verbose_name='End Date')),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='spirtscore',
            name='team_id_providing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_providing', to='app_tutorial.Team'),
        ),
        migrations.AddField(
            model_name='spirtscore',
            name='team_id_receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_receiving', to='app_tutorial.Team'),
        ),
        migrations.AddField(
            model_name='gamereport',
            name='player_id_assist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_assist', to='app_tutorial.Player'),
        ),
        migrations.AddField(
            model_name='gamereport',
            name='player_id_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='app_tutorial.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_id_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='app_tutorial.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_id_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='app_tutorial.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tutorial.Tournament'),
        ),
    ]
